### ISSUE TITLE
JLCPCB CPL Issue 

### ISSUE THREAD

**Issue by Alethi94** [zegonix/custom-cycle7-pcb#1]
![CPL issue](https://github.com/zegonix/custom-cycle7-pcb/assets/130930396/189fe315-0223-48ad-b522-d1d52a6da02f)

Hi, 
just want to say thanks for creating a PCB for the cycle7, mine seems to have some chatter and there's no extras about so this will be great!

When importing into JLCPCB, it is throwing the above error regarding the CPL list. 

could you advise on what it may be?

**Comment by zegonix** [comment]
Hi Alethi

Short answer: this is expected, the Bill of Materials (BOM) is not up to date. For my prototypes I edited the BOM on JLCPCB's website.

This is partly on me, for not adding a readme yet, but this repository is work in progress and unless I make a release I do not take responsibility for potential harm or grieve these sources could cause.

If I remember, I will contact you, once I get the PCB running. Currently I can flash firmware via DFU in Bootloadermode, but the firmware can't seem to connect to the host pc, rendering the PCB useless. If you still want to order the PCB, you can download JLCPCB's example BOM and copy the entries to get a BOM their website accepts. I would advise against that though, as the PCB is not functional at the moment.

Best regards, zegonix

**Comment by zegonix** [comment]
I managed to get the board working and updated my findings from the prototype. I did not update the bill of materials, as the vendors stocks are changing frequently.
You might want to change the design to use the standard 6.25u spacebar design instead of my weird split spacebar (1.25/2.75/2.25). Also consider changing the oscillator circuit to a frequency of 8 MHz, as that is QMKs default for the chip used and a different frequency requires extra configuration. I will provide a link to my configuration in this repositories readme soon though.

Best regards, zegonix
